name: "🚀 Publish to NPM/Github Package Registry"

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    name: 🚀 publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 📚 setup checkout
        uses: actions/checkout@v3
      - name: 🟢 setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

